/* Общие данные для макетов редизайна (черновая раскладка разделов).
   env: PROM | PSI | IFT | null ; seg: ALPHA | SIGMA | null ; copy: код в буфер при клике. */
window.LINKS = {
  sections: [
    { id: "comms", name: "Коммуникации", icon: "chat" },
    { id: "heroes", name: "Герои продаж", icon: "trophy" },
    { id: "kap", name: "КАП и загрузка данных", icon: "upload" },
    { id: "sup", name: "СУП и релизы", icon: "params" },
    { id: "access", name: "Доступы, HR, аудит", icon: "lock" },
    { id: "itsm", name: "Сервис и заявки", icon: "ticket" },
    { id: "data", name: "Данные и аналитика", icon: "report" },
    { id: "docs", name: "Документация", icon: "dicts" },
    { id: "jira", name: "Задачи и команда", icon: "timeline" },
    { id: "repo", name: "Репозитории", icon: "code" },
    { id: "tools", name: "Инструменты", icon: "cmd" }
  ],
  favoriteSeed: ["h-prom-a", "h-prom-s", "h-psi-a", "kap-prom", "kap-psi", "sand", "chat", "jazz", "daily", "mail"],
  links: [
    { id: "chat", s: "comms", t: "СберЧат", u: "https://sberchat.sberbank.ru", icon: "chat" },
    { id: "jazz", s: "comms", t: "SberJazz", u: "https://jazz.sberbank.ru", icon: "video" },
    { id: "mail", s: "comms", t: "Почта", u: "https://mail.sberbank.ru/owa/#path=/mail", seg: "SIGMA", icon: "mail" },
    { id: "daily", s: "comms", t: "Дейли · Герои продаж", u: "https://jazz.sberbank.ru/sber-7g5cqu?psw=OBUVBwADHB0IBRIRXxcLDgcPDw", icon: "video", meet: true },
    { id: "k2", s: "comms", t: "ПКАП встреча (K2)", u: "https://jazz.sberbank.ru/sber-gzdl5c?psw=OEcNEgsBXAZeVwoEVBVLFVFdFw", icon: "video", meet: true },
    { id: "pereval", s: "comms", t: "ПКАП · Перевала Сергей", u: "https://jazz.sberbank.ru/sber-jd9r1x?psw=OBoIEQsCHAVcCg8HVBYLFlMAEg", icon: "video", meet: true },
    { id: "open", s: "comms", t: "Встреча (open)", u: "https://jazz.sberbank.ru/sber-mnv6vl?psw=OEEKAUUdDBVeUQ0XGgkbBlFbEA", icon: "video", meet: true },

    { id: "h-prom-a", s: "heroes", t: "Герои продаж", u: "https://efs-our-business-prom.omega.sbrf.ru/salesheroes", env: "PROM", seg: "ALPHA" },
    { id: "h-prom-s", s: "heroes", t: "Герои продаж", u: "https://sh.sberbank.ru", env: "PROM", seg: "SIGMA" },
    { id: "h-psi-a", s: "heroes", t: "Герои продаж", u: "https://iam-enigma-psi.omega.sbrf.ru/salesheroes", env: "PSI", seg: "ALPHA", copy: "92863949" },
    { id: "h-psi-s", s: "heroes", t: "Герои продаж", u: "https://salesheroes-psi.sigma.sbrf.ru", env: "PSI", seg: "SIGMA" },
    { id: "h-ift-sb", s: "heroes", t: "Герои продаж СБ", u: "https://efs-ift-sb.delta.sbrf.ru/salesheroes", env: "IFT", seg: "SIGMA" },
    { id: "h-ift-gf", s: "heroes", t: "Герои продаж ГФ", u: "https://efs-ift-gf.delta.sbrf.ru/salesheroes", env: "IFT", seg: "SIGMA" },
    { id: "sand", s: "heroes", t: "Песочница", u: "https://bf-enigma-ift.delta.sbrf.ru/", env: "IFT", seg: "SIGMA" },
    { id: "sand21", s: "heroes", t: "Песочница /21", u: "https://bf-enigma-ift.delta.sbrf.ru/21", env: "IFT", seg: "SIGMA" },
    { id: "sandp", s: "heroes", t: "Песочница · профиль", u: "https://bf-enigma-ift.delta.sbrf.ru/salesheroes/gamification/profile", env: "IFT", seg: "SIGMA" },

    { id: "kap-prom", s: "kap", t: "КАП", u: "https://pvlos-sys000001.omega.sbrf.ru/SberDataCorr", env: "PROM", seg: "ALPHA" },
    { id: "kap-psi", s: "kap", t: "КАП", u: "https://tvlos-sys000001.cloud.omega.sbrf.ru", env: "PSI", seg: "ALPHA", copy: "92863949" },
    { id: "kap-psi-new", s: "kap", t: "КАП (new)", u: "https://tslos-sys000002.cloud.omega.sbrf.ru/", env: "PSI", seg: "ALPHA", copy: "92863949" },
    { id: "kap-ift", s: "kap", t: "КАП · data-load", u: "https://tvldw-sys000008.cloud.delta.sbrf.ru:3001/SberDataCorr/PCAP_KKSB_PG_GAME/data-load", env: "IFT", seg: "SIGMA", copy: "92863949" },
    { id: "ctl", s: "kap", t: "Загрузка данных CTL", u: "https://ctl-ift.qa.df.sbrf.ru:9080/#/sign-in", env: "IFT", seg: "SIGMA", copy: "lakomkin-oo" },

    { id: "sup-prom-sk", s: "sup", t: "Редактирование СУП · SK", u: "https://iamproxy-prom-gfsk.ingress.apps.arqgec5q.k8s.ca.sbrf.ru", env: "PROM", seg: "ALPHA" },
    { id: "sup-prom-mg", s: "sup", t: "Редактирование СУП · MG", u: "https://iamproxy-prom-gfmg.ingress.apps.arq6r3xx.k8s.ca.sbrf.ru", env: "PROM", seg: "ALPHA" },
    { id: "sup-psi-sk", s: "sup", t: "Редактирование СУП · SK", u: "https://iamproxy-psi-gfsk.ingress.apps.a6y9tlz1.k8s.omega.sbrf.ru", env: "PSI", seg: "ALPHA" },
    { id: "sup-psi-mg", s: "sup", t: "Редактирование СУП · MG", u: "https://iamproxy-psi-gfmg.ingress.apps.a6y5k6kq.k8s.omega.sbrf.ru", env: "PSI", seg: "ALPHA" },
    { id: "sup-ift-gf", s: "sup", t: "Редактирование СУП · GF", u: "https://iamproxy-ift-gfmg.ingress.apps.a08tr095.k8s.delta.sbrf.ru", env: "IFT", seg: "SIGMA" },
    { id: "dpm", s: "sup", t: "DPM · подтверждение релизов", u: "https://dpm-sigma.sberbank.ru/dpm/front/main/key/EFS_GAME", env: "PROM" },
    { id: "sup-arm", s: "sup", t: "Ссылки на АРМы ПСИ · СУП", u: "https://confluence.ca.sbrf.ru/pages/viewpage.action?pageId=1907494673#", env: "PSI", seg: "ALPHA", icon: "dicts" },
    { id: "sup-doc1", s: "sup", t: "Об управлении СУП пром", u: "https://confluence.sberbank.ru/pages/viewpage.action?pageId=12034673436", seg: "SIGMA", icon: "dicts" },
    { id: "sup-doc2", s: "sup", t: "О доступе к управлению СУП пром", u: "https://confluence.sberbank.ru/pages/viewpage.action?pageId=11862715264", seg: "SIGMA", icon: "dicts" },

    { id: "addr", s: "access", t: "Адресная книга", u: "https://addressbook.omega.sbrf.ru" },
    { id: "acc-a", s: "access", t: "Мои доступы", u: "https://smd.omega.sbrf.ru/SberAccess/#/pa?tab=0", seg: "ALPHA" },
    { id: "acc-s", s: "access", t: "Мои доступы", u: "https://sberu.sigma.sbrf.ru/SberWelcome/#/pa", seg: "SIGMA" },
    { id: "puls-a", s: "access", t: "Пульс", u: "https://hr.ca.sbrf.ru/platform", seg: "ALPHA" },
    { id: "puls-s", s: "access", t: "Пульс", u: "https://hr.sberbank.ru/platform/dashboard", seg: "SIGMA" },
    { id: "friend", s: "access", t: "Друг (new)", u: "https://sberfriend.sberbank.ru/sberfriend/#/dashboard" },
    { id: "tengri", s: "access", t: "Тенгри", u: "https://ci02587203-psi-iam-proxy-client-geo.omega.sbrf.ru", env: "PSI", seg: "ALPHA" },
    { id: "tengri-b", s: "access", t: "Тенгри · логи", u: "https://ci02587203-prom-iam-proxy-main-geo.omega.sbrf.ru/indicator-efs-empl/a/logger/logs?", env: "PROM", seg: "ALPHA" },
    { id: "audit", s: "access", t: "Единый аудит", u: "https://uaudit-psi.omega.sbrf.ru/", env: "PSI", seg: "ALPHA", copy: "92863949" },
    { id: "audit-n", s: "access", t: "Единый аудит (new)", u: "https://uaudit-psi.omega.sbrf.ru/mind_user/", env: "PSI", seg: "ALPHA", copy: "92863949" },

    { id: "esm", s: "itsm", t: "SberESM", u: "https://sberesm.omega.sbrf.ru/efs-ermops-static/app-ops_esm", seg: "ALPHA" },
    { id: "sm-a", s: "itsm", t: "Service Manager", u: "https://servicemanager.omega.sbrf.ru", seg: "ALPHA" },
    { id: "sm-s", s: "itsm", t: "Service Manager", u: "https://adv-gate.sigma.sbrf.ru/Citrix/ADVWeb", seg: "SIGMA" },
    { id: "smg-a", s: "itsm", t: "Портал SM · гайд", u: "https://confluence.ca.sbrf.ru/display/ITSM/ITSM+USER+GUIDE", seg: "ALPHA", icon: "dicts" },
    { id: "smg-s", s: "itsm", t: "Портал SM · гайд", u: "https://sbtatlas.sigma.sbrf.ru/wiki/display/ITSMUG/ITSM+User+Guide", seg: "SIGMA", icon: "dicts" },
    { id: "help", s: "itsm", t: "SberHelp", u: "https://sberhelp.sberbank.ru", seg: "ALPHA" },
    { id: "tfs", s: "itsm", t: "ТФС · пакетная выгрузка", u: "https://selfportal.dev.df.sbrf.ru/support/templates/supportfd" },
    { id: "kaplogs", s: "itsm", t: "Запрос логов КАП-ТФС", u: "https://sberfriend.sberbank.ru/sberfriend/#/application/6BDB0FB3C3604765ABDA49E808B7D0B3", seg: "ALPHA" },

    { id: "qlik", s: "data", t: "Qlik Sense", u: "https://vpokib.ca.sbrf.ru/main/hub", seg: "ALPHA" },
    { id: "qs", s: "data", t: "ДБ QS", u: "https://oko-qs.sigma.sbrf.ru", seg: "SIGMA" },
    { id: "giga", s: "data", t: "ДБ GigaChat", u: "https://oko-qs.sigma.sbrf.ru/prom/sense/app/ea9927f5-64f7-473e-8c3d-c46bd4cea768/sheet/062", seg: "SIGMA" },
    { id: "nav", s: "data", t: "Навигатор", u: "https://navigator.ca.sbrf.ru/overview", seg: "ALPHA" },
    { id: "smd", s: "data", t: "Супермаркет данных", u: "https://sm.data.omega.sbrf.ru/home", seg: "ALPHA" },
    { id: "dtk", s: "data", t: "Дататека", u: "https://datateka.omega.sbrf.ru/desktop", seg: "ALPHA" },
    { id: "varm", s: "data", t: "VARM LabZone i57z", u: "https://a-lz.omega.sbrf.ru", seg: "ALPHA", copy: "omega\\01803187" },
    { id: "xls", s: "data", t: "Терминальный xls", u: "https://cab-snp-cx00001.omega.sbrf.ru", seg: "ALPHA", copy: "omega\\01803187" },
    { id: "hue", s: "data", t: "HUE", u: "http://pklis-mvp003253.labiac.df.sbrf.ru:8888" },
    { id: "jup", s: "data", t: "JupyterHub", u: "https://pklis-mvp003259.labiac.df.sbrf.ru:8000" },
    { id: "amb", s: "data", t: "AMBARI", u: "http://pklis-mvp003251.labiac.df.sbrf.ru:8080" },
    { id: "click", s: "data", t: "Clickstream", u: "https://clickstream-prom.ca.sbrf.ru/frontend", env: "PROM" },

    { id: "efs", s: "docs", t: "ЕФС", u: "https://confluence.sberbank.ru/pages/viewpage.action?pageId=9411070842", seg: "SIGMA" },
    { id: "fab", s: "docs", t: "Фабрика", u: "https://confluence.delta.sbrf.ru/pages/viewpage.action?pageId=9005827798", seg: "SIGMA" },
    { id: "fab-bl", s: "docs", t: "Бэклог фабрики", u: "https://confluence.sberbank.ru/pages/viewpage.action?pageId=17521445497", seg: "SIGMA" },
    { id: "fab-bt", s: "docs", t: "БТ фабрики", u: "https://confluence.sberbank.ru/pages/viewpage.action?pageId=9528155757", seg: "SIGMA" },
    { id: "fab-db", s: "docs", t: "Структура БД фабрики", u: "https://confluence.delta.sbrf.ru/pages/viewpage.action?pageId=9005828031", seg: "SIGMA" },
    { id: "struct", s: "docs", t: "Структура", u: "https://confluence.delta.sbrf.ru/pages/viewpage.action?pageId=9073267075", seg: "SIGMA" },
    { id: "pkap-db", s: "docs", t: "ПКАП база", u: "https://confluence.delta.sbrf.ru/pages/viewpage.action?pageId=10308059296", seg: "SIGMA" },
    { id: "tour", s: "docs", t: "Авто-турниры", u: "https://confluence.sberbank.ru/pages/viewpage.action?pageId=11671348420", seg: "SIGMA" },
    { id: "testusers", s: "docs", t: "Тестовые пользователи", u: "https://confluence.sberbank.ru/pages/viewpage.action?pageId=11219247593", env: "IFT", seg: "SIGMA" },
    { id: "incid", s: "docs", t: "Реестр инцидентов", u: "https://confluence.sberbank.ru/pages/viewpage.action?pageId=24253043818", seg: "SIGMA" },
    { id: "insider", s: "docs", t: "График периодов инсайдер", u: "https://confluence.ca.sbrf.ru/pages/viewpage.action?pageId=8956707657", seg: "ALPHA" },

    { id: "sprint", s: "jira", t: "Спринт", u: "https://jira.sberbank.ru/secure/RapidBoard.jspa?rapidView=32210&view=planning.nodetail", seg: "SIGMA" },
    { id: "sprint-t", s: "jira", t: "Задачи спринта", u: "https://jira.sberbank.ru/secure/StructureBoard.jspa?s=24740#", seg: "SIGMA" },
    { id: "q2", s: "jira", t: "Задачи 2 кв · HERO-4358", u: "https://jira.sberbank.ru/browse/HERO-4358", seg: "SIGMA" },
    { id: "q1", s: "jira", t: "Задачи 1 кв", u: "https://jira.sberbank.ru/secure/RapidBoard.jspa?rapidView=32210&view=planning.nodetail", seg: "SIGMA" },
    { id: "pkap-j", s: "jira", t: "ПКАП · структура", u: "https://jira.delta.sbrf.ru/secure/StructureBoard.jspa?s=19119#", seg: "SIGMA" },
    { id: "board", s: "jira", t: "Доска команд", u: "https://agile.sber.ru/dashboard/#/", seg: "SIGMA" },
    { id: "esr", s: "jira", t: "ЕСР", u: "https://esr.sigma.sbrf.ru", seg: "SIGMA" },
    { id: "devops", s: "jira", t: "DevOps-портал", u: "https://sso.devopsportal.sigma.sbrf.ru/dop/#/", seg: "SIGMA" },

    { id: "r-and", s: "repo", t: "Мобилка Android", u: "https://stash.delta.sbrf.ru/projects/RMKIB_MOBILE/repos/game_mobile_android/browse", seg: "SIGMA" },
    { id: "r-ios", s: "repo", t: "Мобилка iOS", u: "https://stash.delta.sbrf.ru/projects/RMKIB_MOBILE/repos/game_mobile_ios/browse", seg: "SIGMA" },
    { id: "r-front", s: "repo", t: "Фронт ЕФС", u: "https://stash.delta.sbrf.ru/projects/RMKIBPL/repos/gamification/browse", seg: "SIGMA" },
    { id: "r-back", s: "repo", t: "Бэк ЕФС", u: "https://stash.delta.sbrf.ru/projects/RMKIB/repos/rmkib.gamification/browse", seg: "SIGMA" },
    { id: "r-sowa", s: "repo", t: "SOWA", u: "https://stash.delta.sbrf.ru/projects/RMKIB/repos/rmkib.sowa.game/browse", seg: "SIGMA" },
    { id: "r-bps", s: "repo", t: "Фабрика БПС", u: "https://stash.delta.sbrf.ru/projects/KKSBFACT/repos/gamification-bps-service/browse", seg: "SIGMA" },
    { id: "r-fab", s: "repo", t: "Фабрика · пространство", u: "https://stash.delta.sbrf.ru/projects/KKSBFACT", seg: "SIGMA" },

    { id: "decoder", s: "tools", t: "Декодер permission", tool: "decoder", icon: "cmd" },
    { id: "role", s: "tools", t: "Проверка роли (ПСИ)", tool: "role", env: "PSI", icon: "checks" }
  ]
};
